config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :topics, only: [:index, :show] do
    resources :quizzes, only: [:index, :show, :new, :create, :update]
  end

  root to: 'topics#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :quiz

  validates :quiz_id, :user_id, presence: true
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :topic
  has_many :answers
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :quizzes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_topic
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    # redirect to show or to new quiz path randomly
    if (rand * 10).to_i > 9
      redirect_to new_topics_quizzes_path(@topic)
    else
      # puts 'WHAT'
      # puts @topic.quizzes.all.inspect
      # puts @topic.inspect
      redirect_to topic_quiz_path(id: @topic.quizzes.shuffle.first, topic_id: @topic)
    end
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new(topic: Topic.first)
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params.merge(topic: Topic.first))

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to topic_quiz_path(@quiz, @quiz.topic), notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: topic_quiz_path(@quiz, @quiz.topic) }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    answer = current_user.answers.create!(quiz: @quiz, correctness: (params[:answer].to_i > 0) )

    respond_to do |format|
      format.html { redirect_to topic_quiz_path(@quiz, @quiz.topic), notice: 'Your answer is saved.' }
      format.json { render :show, status: :ok, location: topic_quiz_path(@quiz, @quiz.topic) }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_quiz
    @quiz = @topic.quizzes.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def quiz_params
    params.require(:quiz).permit(:question, :good_answer, :bad_answer)
  end

  # # GET /quizzes/1/edit
  # def edit
  # end

  # # DELETE /quizzes/1
  # # DELETE /quizzes/1.json
  # def destroy
  #   @quiz.destroy
  #   respond_to do |format|
  #     format.html { redirect_to topic_quizzes_path(@quiz.topic), notice: 'Quiz was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:name)
  end

  # # GET /topics/new
  # def new
  #   @topic = Topic.new
  # end
  #
  # # GET /topics/1/edit
  # def edit
  # end
  #
  # # POST /topics
  # # POST /topics.json
  # def create
  #   @topic = Topic.new(topic_params)
  #
  #   respond_to do |format|
  #     if @topic.save
  #       format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
  #       format.json { render :show, status: :created, location: @topic }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @topic.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /topics/1
  # # PATCH/PUT /topics/1.json
  # def update
  #   respond_to do |format|
  #     if @topic.update(topic_params)
  #       format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @topic }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @topic.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /topics/1
  # # DELETE /topics/1.json
  # def destroy
  #   @topic.destroy
  #   respond_to do |format|
  #     format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizzy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body role="document">
    <div class="logo"><%= link_to 'Quizzy', root_path %></div>
    <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <p id="notice"><%= notice %></p>
            <%= link_to 'Log out', destroy_user_session_path, method: 'delete', class: 'log_out' %>
            <%= yield %>
          </div>
          <div class="col-md-6 visible-md visible-lg">
            <h2>What is Quizzy?</h2>
            <p>Quizzy is a quiz game. It helps you to became a master in a topic. As you solve quizzes you will be asked to write new ones. So it is a growing knowledge base.</p>
            <h3>The science behind</h3>
            <p>If you are able to correctly answer to a question in 4 following days then you learned it for forever. You successfully saved it into your short-middle-long term memory. Congrat!</p>
            <h2>Top scores</h2>
            <p>...</p>
          </div>
        </div>
    </div>
</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for([@quiz.topic, @quiz]) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :good_answer %><br>
    <%= f.text_area :good_answer %>
  </div>
  <div class="field">
    <%= f.label :bad_answer %><br>
    <%= f.text_area :bad_answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

app/views/quizzes/index.html.erb
<h1>Listing quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Good answer</th>
      <th>Bad answer</th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.question %></td>
        <td><%= quiz.good_answer %></td>
        <td><%= quiz.bad_answer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_topic_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

app/views/quizzes/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Quizzy", root_path %></li>
  <li><%= link_to @quiz.topic.name, @topic, class: 'active' %></li>
</ol>

<h1 data-url="<%= topic_quiz_path(@quiz.topic, @quiz) %>"><%= @quiz.question %></h1>

<% [:good, :bad].shuffle.each do |answer| %>
    <button type="button" class="quiz-answer btn btn-default btn-lg btn-block" data-correctness="<%= answer == :good ? 1 : 0 %>"><%= answer == :good ? @quiz.good_answer : @quiz.bad_answer %></button>
<% end %>

<br>

<%= link_to "Next question", topic_quizzes_path(@quiz.topic), class: 'quiz-forward btn btn-default btn-lg btn-block', style: "display:none" %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>What's your topic?</h1>

<ul class="list-group">
    <% @topics.each do |topic| %>
      <li class="list-group-item">
        <h2><%= link_to topic.name, topic %></h2>
        <span class="badge"><%= topic.quizzes.count %></span>
        <%= topic.quizzes.limit(5).map(&:question).join(' ') %>
      </li>
    <% end %>
</ul>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<p>
  <strong>Quizzes:</strong>
  <%= @topic.quizzes.limit(5).map(&:question).join(', ') %>
</p>

<br>

<div class="text-center">
  <%= link_to 'Start playing!', topic_quizzes_path(@topic), class: 'btn btn-success btn-lg' %>
</div>